CREATE SEQUENCE GLOBAL_PLACE_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE
    NOORDER;

ALTER TABLE PLACE
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE RESTAURANT
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE TOUR
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE ACCOMMODATION
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );