CREATE SEQUENCE GLOBAL_PLACE_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE
    NOORDER;

UPDATE PLACE
SET "view" = 0
WHERE "view" IS NULL;
UPDATE PLACE
SET "like" = 0
WHERE "like" IS NULL;


ALTER TABLE PLACE
    MODIFY ("view" NUMBER(10) DEFAULT 0 NOT NULL);
ALTER TABLE PLACE
    MODIFY ("like" NUMBER(10) DEFAULT 0 NOT NULL);