CREATE SEQUENCE GLOBAL_PLACE_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE
    NOORDER;

TRUNCATE TABLE tour;
TRUNCATE TABLE ACCOMMODATION;
TRUNCATE TABLE RESTAURANT;
TRUNCATE TABLE place;
TRUNCATE TABLE tour_image;
TRUNCATE TABLE restaurant_image;
TRUNCATE TABLE accommodation_image;

ALTER TABLE PLACE
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE RESTAURANT
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE TOUR
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );
ALTER TABLE ACCOMMODATION
    ADD (
        ID NUMBER(10) DEFAULT GLOBAL_PLACE_SEQ.NEXTVAL PRIMARY KEY
        );


UPDATE PLACE
SET "view" = 0
WHERE "view" IS NULL;
UPDATE PLACE
SET "like" = 0
WHERE "like" IS NULL;


ALTER TABLE PLACE
    MODIFY ("view" NUMBER(10) DEFAULT 0 NOT NULL);
ALTER TABLE PLACE
    MODIFY ("like" NUMBER(10) DEFAULT 0 NOT NULL);