CREATE TABLE tag
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    name       VARCHAR2(7)                              NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

CREATE TABLE place_tag
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    place_id   INTEGER                                  NOT NULL,
    tag_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_place_tag PRIMARY KEY (id)
);

ALTER TABLE place_tag
    ADD CONSTRAINT uk_place_tag_place_and_tag UNIQUE (place_id, tag_id);

ALTER TABLE place_tag
    ADD CONSTRAINT FK_PLACE_TAG_ON_PLACE FOREIGN KEY (place_id) REFERENCES place (id);

CREATE INDEX idx_place_tag_place ON place_tag (place_id);

ALTER TABLE place_tag
    ADD CONSTRAINT FK_PLACE_TAG_ON_TAG FOREIGN KEY (tag_id) REFERENCES tag (id);

CREATE INDEX idx_place_tag_tag ON place_tag (tag_id);

CREATE TABLE PLACE_THEME (
                             ID         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             PLACE_ID   INTEGER NOT NULL,
                             THEME_ID   INTEGER NOT NULL,
                             CREATED_AT TIMESTAMP NOT NULL,
                             CONSTRAINT PK_PLACE_THEME PRIMARY KEY (ID)
                         );

ALTER TABLE PLACE_THEME
    ADD CONSTRAINT fk_place_theme_place
        FOREIGN KEY (PLACE_ID)
            REFERENCES PLACE (ID);

ALTER TABLE PLACE_THEME
    ADD CONSTRAINT fk_place_theme_theme
        FOREIGN KEY (THEME_ID)
            REFERENCES THEME (ID);

ALTER TABLE PLACE_THEME
    ADD CONSTRAINT uk_place_theme_place_and_theme
        UNIQUE (PLACE_ID, THEME_ID);

CREATE INDEX idx_place_theme_place
    ON PLACE_THEME (PLACE_ID);

CREATE INDEX idx_place_theme_theme
    ON PLACE_THEME (THEME_ID);
