CREATE TABLE tag
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    name       VARCHAR2(7)                              NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

CREATE INDEX idx_tag_name ON tag (name);
