-- ACCOMMODATION_IMAGE_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE ACCOMMODATION_IMAGE_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; -- ORA-00955: sequence already exists
END;
/
 
-- ACCOMMODATION_REVIEW_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE ACCOMMODATION_REVIEW_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- ACCOMMODATION_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE ACCOMMODATION_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- ATTRACTION_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE ATTRACTION_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- MENU_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE MENU_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- RESTAURANT_IMAGE_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE RESTAURANT_IMAGE_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- RESTAURANT_REVIEW_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE RESTAURANT_REVIEW_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- ROOM_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE ROOM_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- TOUR_IMAGE_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE TOUR_IMAGE_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- TOUR_REVIEW_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE TOUR_REVIEW_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
 
-- GLOBAL_PLACE_SEQ
BEGIN
  EXECUTE IMMEDIATE q'[CREATE SEQUENCE GLOBAL_PLACE_SEQ START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE NOORDER]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
