ALTER TABLE TOUR        DROP CONSTRAINT FK_TOUR_CATEGORY;
ALTER TABLE RESTAURANT  DROP CONSTRAINT FK_RESTAURANT_CATEGORY;
ALTER TABLE ACCOMMODATION DROP CONSTRAINT FK_ACCOMMODATION_CATEGORY;
/

ALTER TABLE TOUR
    ADD CONSTRAINT FK_TOUR_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/
ALTER TABLE RESTAURANT
    ADD CONSTRAINT FK_RESTAURANT_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/
ALTER TABLE ACCOMMODATION
    ADD CONSTRAINT FK_ACCOMMODATION_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/