BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE TOUR DROP CONSTRAINT FK_TOUR_CATEGORY';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN -- ORA-02443: 제약조건이 존재하지 않음
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE RESTAURANT DROP CONSTRAINT FK_RESTAURANT_CATEGORY';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE ACCOMMODATION DROP CONSTRAINT FK_ACCOMMODATION_CATEGORY';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
END IF;
END;
/

ALTER TABLE TOUR
    ADD CONSTRAINT FK_TOUR_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/

ALTER TABLE RESTAURANT
    ADD CONSTRAINT FK_RESTAURANT_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/

ALTER TABLE ACCOMMODATION
    ADD CONSTRAINT FK_ACCOMMODATION_CATEGORY
        FOREIGN KEY (PLACE_LCLS_CATEGORY_ID)
            REFERENCES PLACE_LCLS_CATEGORY (ID)
    ENABLE VALIDATE
/
