CREATE TABLE trip_sok_user
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at   TIMESTAMP                                NOT NULL,
    created_at   TIMESTAMP                                NOT NULL,
    name         VARCHAR2(100)                            NOT NULL,
    social_type  VARCHAR2(255)                            NOT NULL,
    social_id    VARCHAR2(255),
    email        VARCHAR2(100)                            NOT NULL,
    password     VARCHAR2(255),
    country_code VARCHAR2(255),
    language     VARCHAR2(255),
    role         VARCHAR2(255)                            NOT NULL,
    CONSTRAINT pk_tripsokuser PRIMARY KEY (id)
);

ALTER TABLE trip_sok_user
    ADD CONSTRAINT uc_tripsokuser_email UNIQUE (email);

CREATE TABLE theme
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    type       VARCHAR2(255),
    CONSTRAINT pk_theme PRIMARY KEY (id)
);

CREATE TABLE interest_theme
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    user_id    INTEGER,
    theme_id   INTEGER,
    CONSTRAINT pk_interesttheme PRIMARY KEY (id)
);

ALTER TABLE interest_theme
    ADD CONSTRAINT FK_INTERESTTHEME_ON_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);

ALTER TABLE interest_theme
    ADD CONSTRAINT FK_INTERESTTHEME_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id);
