CREATE TABLE interest_place
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    user_id    INTEGER                                  NOT NULL,
    place_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_interestplace PRIMARY KEY (id)
);

ALTER TABLE interest_place
    ADD CONSTRAINT uk_interest_place_user_place UNIQUE (user_id, place_id);

ALTER TABLE interest_place
    ADD CONSTRAINT FK_INTERESTPLACE_ON_PLACE FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE;

CREATE INDEX idx_interest_place_place_id ON interest_place (place_id);

ALTER TABLE interest_place
    ADD CONSTRAINT FK_INTERESTPLACE_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id) ON DELETE CASCADE;

CREATE INDEX idx_interest_place_user_id ON interest_place (user_id);
