ALTER TABLE TRIP_SOK_USER
    RENAME COLUMN NAME TO NICKNAME;

ALTER TABLE TRIP_SOK_USER
    DROP COLUMN COUNTRY_CODE;

ALTER TABLE TRIP_SOK_USER
    ADD (
        first_name    VARCHAR2(50),
        last_name     VARCHAR2(50)
        );
