CREATE TABLE tag_tr
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    tag_id     INTEGER                                  NOT NULL,
    locale     NUMBER(5)                                NOT NULL,
    name       VARCHAR2(100)                            NOT NULL,
    CONSTRAINT pk_tag_tr PRIMARY KEY (id)
);

ALTER TABLE tag_tr
    ADD CONSTRAINT uk_place_tag_tag_and_locale UNIQUE (tag_id, locale);

CREATE INDEX idx_place_tag_name ON tag_tr (name);

ALTER TABLE tag_tr
    ADD CONSTRAINT FK_TAG_TR_ON_TAG FOREIGN KEY (tag_id) REFERENCES tag (id);

CREATE TABLE theme_tr
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP                                NOT NULL,
    theme_id   INTEGER                                  NOT NULL,
    locale     NUMBER(5)                                NOT NULL,
    name       VARCHAR2(100)                            NOT NULL,
    CONSTRAINT pk_theme_tr PRIMARY KEY (id)
);

ALTER TABLE theme_tr
    ADD CONSTRAINT uk_theme_tr_theme_and_locale UNIQUE (theme_id, locale);

ALTER TABLE theme_tr
    ADD CONSTRAINT FK_THEME_TR_ON_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);
