CREATE TABLE trip_plan
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at       TIMESTAMP                                NOT NULL,
    created_at       TIMESTAMP                                NOT NULL,
    trip_date        date,
    start_time       DATE,
    number_of_people INTEGER,
    status           VARCHAR2(20)                        NOT NULL,
    user_id          INTEGER                                  NOT NULL,
    version          INTEGER                                  NOT NULL,
    CONSTRAINT pk_trip_plan PRIMARY KEY (id)
);

ALTER TABLE trip_plan
    ADD CONSTRAINT uk_trip_plan_user UNIQUE (user_id);

ALTER TABLE trip_plan
    ADD CONSTRAINT FK_TRIP_PLAN_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id);

CREATE TABLE visit_spot
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trip_plan_id INTEGER                                  NOT NULL,
    place_id     INTEGER                                  NOT NULL,
    order_index  INTEGER                                  NOT NULL,
    memo         VARCHAR2(160),
    CONSTRAINT pk_visit_spot PRIMARY KEY (id)
);

ALTER TABLE visit_spot
    ADD CONSTRAINT FK_VISIT_SPOT_ON_PLACE FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE;

ALTER TABLE visit_spot
    ADD CONSTRAINT FK_VISIT_SPOT_ON_TRIP_PLAN FOREIGN KEY (trip_plan_id) REFERENCES trip_plan (id) ON DELETE CASCADE;

CREATE INDEX idx_visit_spot_trip_plan_id ON visit_spot (trip_plan_id);
