ALTER TABLE trip_plan
    DROP CONSTRAINT FK_TRIP_PLAN_ON_USER;

ALTER TABLE trip_plan
    ADD CONSTRAINT FK_TRIP_PLAN_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id) ON DELETE CASCADE;

ALTER TABLE interest_theme
    DROP CONSTRAINT FK_INTERESTTHEME_ON_USER;

ALTER TABLE interest_theme
    ADD CONSTRAINT FK_INTERESTTHEME_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id) ON DELETE CASCADE;
