CREATE TABLE booking
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP                                NOT NULL,
    user_id          INTEGER,
    contact_email    VARCHAR2(255)                            NOT NULL,
    user_name        VARCHAR2(255)                            NOT NULL,
    trip_date        date                                     NOT NULL,
    start_time       DATE                                     NOT NULL,
    number_of_people INTEGER                                  NOT NULL,
    order_number     VARCHAR2(255)                            NOT NULL,
    amount           INTEGER                                  NOT NULL,
    payment_key      VARCHAR2(255)                            NOT NULL,
    locale           VARCHAR2(20)                             NOT NULL,
    status           VARCHAR2(20)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD CONSTRAINT uc_booking_order_number UNIQUE (order_number);

ALTER TABLE booking
    ADD CONSTRAINT uc_booking_payment_key UNIQUE (payment_key);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES trip_sok_user (id);

CREATE INDEX idx_booking_user_id ON booking (user_id);

CREATE TABLE booking_spot
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id  INTEGER                                  NOT NULL,
    place_id    INTEGER                                  NOT NULL,
    place_name  VARCHAR2(255)                            NOT NULL,
    address     VARCHAR2(255)                            NOT NULL,
    latitude    DECIMAL                                  NOT NULL,
    longitude   DECIMAL                                  NOT NULL,
    order_index INTEGER                                  NOT NULL,
    memo        VARCHAR2(255),
    CONSTRAINT pk_bookingspot PRIMARY KEY (id)
);

ALTER TABLE booking_spot
    ADD CONSTRAINT FK_BOOKINGSPOT_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES booking (id);
