CREATE INDEX idx_accommodation_image_place ON ACCOMMODATION_IMAGE(ACCOMMODATION_ID);
CREATE INDEX idx_place_tr_place ON PLACE_TR(PLACE_ID);
CREATE INDEX idx_restaurant_image_place ON RESTAURANT_IMAGE(RESTAURANT_ID);
CREATE INDEX idx_tour_image_place ON TOUR_IMAGE(TOUR_ID);
