CREATE TABLE place_lcls_category (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lcls_systm1_code  VARCHAR2(10)  NOT NULL,
    lcls_systm1_name  VARCHAR2(100) NOT NULL,
    lcls_systm2_code  VARCHAR2(20)  NOT NULL,
    lcls_systm2_name  VARCHAR2(100) NOT NULL,
    lcls_systm3_code  VARCHAR2(20)  NOT NULL,
    lcls_systm3_name  VARCHAR2(200) NOT NULL,


    CONSTRAINT pk_tour_lcls_category PRIMARY KEY (id),
    CONSTRAINT uq_tour_lcls_category_cd UNIQUE (lcls_systm3_code)
);
