version: '3.8'
services:
  elasticsearch:
    build:
      context: ./infra/elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_URL}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    depends_on:
      - elasticsearch
  redis-service:
    build:
      context: ./infra/redis
      dockerfile: Dockerfile
    image: local/redis-service:${IMAGE_TAG:-local}
    ports:
      - "6379:6379"
  oracle-free:
    image: gvenzl/oracle-free:latest
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${DB_PASSWORD}
      ORACLE_DATABASE: FREEPDB1
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - foracle_data:/opt/oracle/oradata
    restart: unless-stopped
  backend-service:
    build:
      context: ./back/tripsok_back
      dockerfile: Dockerfile
    image: local/backend-service:${IMAGE_TAG:-local}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
volumes:
  es_data:
  foracle_data: