FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.0
RUN elasticsearch-plugin install analysis-nori
RUN elasticsearch-plugin install analysis-kuromoji
RUN elasticsearch-plugin install analysis-smartcn
