client:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
    refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
    email-verification-token-expiration-time: ${JWT_EMAIL_VERIFICATION_TOKEN_EXPIRATION_TIME}
    oauth2-access-token-expiration-time: ${JWT_OAUTH2_ACCESS_TOKEN_EXPIRATION_TIME}
  ai:
    github-token: ${GIT_HUB_TOKEN}
