# application-flyway.yml
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 0
logging:
  level:
    org.flywaydb.core: DEBUG