spring:
  config.activate.on-profile: stable
  datasource:
    url: ${DB_STABLE_URL}
    username: ${DB_STABLE_USERNAME}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    show-sql: false

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: WARN

sentry:
  dsn: https://ab2b2a9b6e761c557f213756101643be@o4505148859023360.ingest.us.sentry.io/4510284084477952
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  # Enable sending logs to Sentry
  logs:
    enabled: true
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  environment: stable
