server:
  port: 8080

spring:
  config:
    import: optional:classpath:.env
  profiles:
    include:
      - flyway
      - jwt
      - oauth2
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      password: ${REDIS_PASSWORD}
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    auth: true
    starttls: true
    debug: true
    connectiontimeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
